#这是[Function]的配置文件


#基础配置
#  服务器名字
server_name: FunctionServer
#  独立服务器(LocalServer)ip
local_server_ip: 127.0.0.1
#  独立服务器(LocalServer)端口
local_server_port: 846


#功能管理
#  是否启用账号管理(/login)(根路由为注册，audit路由为审核，cloud_message路由为云消息)
player_protect: true
#  是否启用AI聊天(使用“-chat 内容”触发)
chat_with_AI: true
#  是否启用猫娘苏洛(使用“-苏洛 内容”触发)
chat_with_CatGirl: true
#  是否启用云消息
cloud_message: true
#  是否向本地服务器同步玩家在线信息
update_player_state: true
#  是否启用头颅获取(/get_player_head)
get_player_head: true


#参数配置
#  [账号管理]注册页的ip/端口
website_reg:
#  普通玩家获取玩家头颅的间隔(以秒为单位)
get_player_head_interval: 1800
#   猫娘的记忆时长(以秒为单位,设为0为禁用记忆)
cat_girl_memories_time: 300